In [1]:
# Introduce data as list of tuples splitted by date

orders_2022_02_04 = [
    (9423517, '2022-02-04', 9001),
    (4626232, '2022-02-04', 9003),
    (9423534, '2022-02-04', 9001)
]

orders_2022_02_05 = [
    (9423679, '2022-02-05', 9002),
    (4626377, '2022-02-05', 9003),
    (4626412, '2022-02-05', 9004)
]

orders_2022_02_06 = [
    (9423783, '2022-02-06', 9002),
    (4626490, '2022-02-06', 9004)
]

In [2]:
# Join into a single list using `+` operator
orders = orders_2022_02_04 + orders_2022_02_05 + orders_2022_02_06

In [3]:
display(orders)

[(9423517, '2022-02-04', 9001),
 (4626232, '2022-02-04', 9003),
 (9423534, '2022-02-04', 9001),
 (9423679, '2022-02-05', 9002),
 (4626377, '2022-02-05', 9003),
 (4626412, '2022-02-05', 9004),
 (9423783, '2022-02-06', 9002),
 (4626490, '2022-02-06', 9004)]

In [4]:
# Dictionaries can be "combined" using `**` operator

extra_fields_9423517 = {
    'ShippingInstrustions' : {
        'name' : 'John Silver',
        'Phone' : [
            {
                'type' : 'Office',
                'number' : '809-123-9309'
            },
            {
                'type' : 'Mobile',
                'number' : '417-123-4567'
            }
        ]
    }
}

order_9423517 = {
    'OrderNo': 9423517,
    'Date': '2022-02-04',
    'Empno': 9001
}

order_9423517 = {
    **order_9423517,
    **extra_fields_9423517
}

In [5]:
display(order_9423517)

{'OrderNo': 9423517,
 'Date': '2022-02-04',
 'Empno': 9001,
 'ShippingInstrustions': {'name': 'John Silver',
  'Phone': [{'type': 'Office', 'number': '809-123-9309'},
   {'type': 'Mobile', 'number': '417-123-4567'}]}}

In [6]:
details = [
 (9423517, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, 'Socks', 'Vans', 15.0, 1),
 (4626232, 'Jeans', 'Quiksilver', 82.0, 1),
 (9423534, 'Socks', 'DC', 10.0, 2),
 (9423534, 'Socks', 'Quiksilver', 12.0, 2),
 (9423679, 'T-shirt', 'Patagonia', 35.0, 1),
 (4626377, 'Hoody', 'Animal', 44.0, 1),
 (4626377, 'Cargo Shorts', 'Animal', 38.0, 1),
 (4626412, 'Shirt', 'Volcom', 78.0, 1),
 (9423783, 'Boxer Shorts', 'Superdry', 30.0, 2),
 (9423783, 'Shorts', 'Globe', 26.0, 1),
 (4626490, 'Cargo Shorts', 'Billabong', 54.0, 1),
 (4626490, 'Sweater', 'Dickies', 56.0, 1)
]

# Order Details must contain the tuples with matching order numbers, merge them into a single tuple, and store all the tuples in a list
order_details = []

for o in orders:
    for d in details:
        if o[0] == d[0]:
            # skip the first element as it is the order number which is already insterted by `o`
            order_details.append(o + d[1:])

display(order_details)

[(9423517, '2022-02-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, '2022-02-04', 9001, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, '2022-02-04', 9003, 'Socks', 'Vans', 15.0, 1),
 (4626232, '2022-02-04', 9003, 'Jeans', 'Quiksilver', 82.0, 1),
 (9423534, '2022-02-04', 9001, 'Socks', 'DC', 10.0, 2),
 (9423534, '2022-02-04', 9001, 'Socks', 'Quiksilver', 12.0, 2),
 (9423679, '2022-02-05', 9002, 'T-shirt', 'Patagonia', 35.0, 1),
 (4626377, '2022-02-05', 9003, 'Hoody', 'Animal', 44.0, 1),
 (4626377, '2022-02-05', 9003, 'Cargo Shorts', 'Animal', 38.0, 1),
 (4626412, '2022-02-05', 9004, 'Shirt', 'Volcom', 78.0, 1),
 (9423783, '2022-02-06', 9002, 'Boxer Shorts', 'Superdry', 30.0, 2),
 (9423783, '2022-02-06', 9002, 'Shorts', 'Globe', 26.0, 1),
 (4626490, '2022-02-06', 9004, 'Cargo Shorts', 'Billabong', 54.0, 1),
 (4626490, '2022-02-06', 9004, 'Sweater', 'Dickies', 56.0, 1)]

In case we have missing "columns" (fields) in part of our data we might want to still join both sets but a default value must be specified at the moment of performing this join.

In [7]:
# Append an item that doesnt matches order data
details.append((4626592, 'Shorts', 'Protest', 48.0, 1))

In [8]:
# Compact version of aboves loop
orders_details = [[o for o in orders if d[0] == o][0] + d[1:] for d in details]

IndexError: list index out of range

When theres a unmatched order number the slice/range operation fails

In [9]:
# Fixes the index out of bounds issue but stills doesnt includes the new 
orders_details = [[o for o in orders if d[0] in o][0] + d[1:] for d in details if d[0] in [o[0] for o in orders]]
display(orders_details)

[(9423517, '2022-02-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, '2022-02-04', 9001, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, '2022-02-04', 9003, 'Socks', 'Vans', 15.0, 1),
 (4626232, '2022-02-04', 9003, 'Jeans', 'Quiksilver', 82.0, 1),
 (9423534, '2022-02-04', 9001, 'Socks', 'DC', 10.0, 2),
 (9423534, '2022-02-04', 9001, 'Socks', 'Quiksilver', 12.0, 2),
 (9423679, '2022-02-05', 9002, 'T-shirt', 'Patagonia', 35.0, 1),
 (4626377, '2022-02-05', 9003, 'Hoody', 'Animal', 44.0, 1),
 (4626377, '2022-02-05', 9003, 'Cargo Shorts', 'Animal', 38.0, 1),
 (4626412, '2022-02-05', 9004, 'Shirt', 'Volcom', 78.0, 1),
 (9423783, '2022-02-06', 9002, 'Boxer Shorts', 'Superdry', 30.0, 2),
 (9423783, '2022-02-06', 9002, 'Shorts', 'Globe', 26.0, 1),
 (4626490, '2022-02-06', 9004, 'Cargo Shorts', 'Billabong', 54.0, 1),
 (4626490, '2022-02-06', 9004, 'Sweater', 'Dickies', 56.0, 1)]

In [10]:
# In order to include the missing order we must set a de-fault value when the orders list is missing an entry for a provided order detail
order_details_right = [[o for o in orders if d[0] in o][0] + d[1:] if d[0] in [o[0] for o in orders] else (d[0], None, None) + d[1:] for d in details]
display(order_details_right)

[(9423517, '2022-02-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, '2022-02-04', 9001, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, '2022-02-04', 9003, 'Socks', 'Vans', 15.0, 1),
 (4626232, '2022-02-04', 9003, 'Jeans', 'Quiksilver', 82.0, 1),
 (9423534, '2022-02-04', 9001, 'Socks', 'DC', 10.0, 2),
 (9423534, '2022-02-04', 9001, 'Socks', 'Quiksilver', 12.0, 2),
 (9423679, '2022-02-05', 9002, 'T-shirt', 'Patagonia', 35.0, 1),
 (4626377, '2022-02-05', 9003, 'Hoody', 'Animal', 44.0, 1),
 (4626377, '2022-02-05', 9003, 'Cargo Shorts', 'Animal', 38.0, 1),
 (4626412, '2022-02-05', 9004, 'Shirt', 'Volcom', 78.0, 1),
 (9423783, '2022-02-06', 9002, 'Boxer Shorts', 'Superdry', 30.0, 2),
 (9423783, '2022-02-06', 9002, 'Shorts', 'Globe', 26.0, 1),
 (4626490, '2022-02-06', 9004, 'Cargo Shorts', 'Billabong', 54.0, 1),
 (4626490, '2022-02-06', 9004, 'Sweater', 'Dickies', 56.0, 1),
 (4626592, None, None, 'Shorts', 'Protest', 48.0, 1)]

Get a sum over all items

In [11]:
sum(price * quantity for _, _, _, _, _, price, quantity in order_details_right)

779.0

In [ ]:
# Filter out orders not present in `orders` list by checkitn
sum(price * quantity for _, date, _, _, _, price, quantity in order_details_right if date != None)

## Concatenating NumPy Arrays

In [2]:
import numpy as np

jeff_salary = [2700, 3000, 3000]
nick_salary = [2600, 2800, 2800]
tom_salary = [2300, 2500, 2500]

base_salary1 = np.array([jeff_salary, nick_salary, tom_salary])
display(base_salary1)

array([[2700, 3000, 3000],
       [2600, 2800, 2800],
       [2300, 2500, 2500]])

In [3]:
maya_salary = [2200, 2400, 3000]
john_salary = [2500, 2700, 2700]

base_salary2 = np.array([maya_salary, john_salary])
display(base_salary2)

array([[2200, 2400, 3000],
       [2500, 2700, 2700]])

In [5]:
base_salary = np.concatenate((base_salary1, base_salary2), axis=0) # axis=0 concatenates vertically
display(base_salary)

array([[2700, 3000, 3000],
       [2600, 2800, 2800],
       [2300, 2500, 2500],
       [2200, 2400, 3000],
       [2500, 2700, 2700]])

With both salary arrays merged into one, we can now open scenario for a case where a single month salary per employee is also introduced.
In this case we want to concatenate an array of salaries that holds the same order as of employees.

In [6]:
# Introduces a new month salary for each employee where each item (array in the 2nd dimension) belongs to an employee
new_month_salary = [
    [3000],
    [2900],
    [2500],
    [2500],
    [2700]]

In [8]:
# Concatenates the `new_month_salary` to the `base_salary` array. Uses axis=1 to concatenate horizontally
base_salary = np.concatenate((base_salary, new_month_salary), axis=1)
display(base_salary)

array([[2700, 3000, 3000, 3000],
       [2600, 2800, 2800, 2900],
       [2300, 2500, 2500, 2500],
       [2200, 2400, 3000, 2500],
       [2500, 2700, 2700, 2700]])

In [10]:
upcoming_months = [
    [3000, 3200],
    [2900, 2900],
    [2500, 2900],
    [3000, 3000],
    [2900, 2900],
]

base_salary = np.concatenate((base_salary, upcoming_months), axis=1)
display(base_salary)

array([[2700, 3000, 3000, 3000, 3000, 3200],
       [2600, 2800, 2800, 2900, 2900, 2900],
       [2300, 2500, 2500, 2500, 2500, 2900],
       [2200, 2400, 3000, 2500, 3000, 3000],
       [2500, 2700, 2700, 2700, 2900, 2900]])

In [13]:
new_employee_salary = [
    [0, 0, 0, 0, 0, 2900]
]

base_salary = np.concatenate((base_salary, new_employee_salary), axis=0)
display(base_salary)

array([[2700, 3000, 3000, 3000, 3000, 3200],
       [2600, 2800, 2800, 2900, 2900, 2900],
       [2300, 2500, 2500, 2500, 2500, 2900],
       [2200, 2400, 3000, 2500, 3000, 3000],
       [2500, 2700, 2700, 2700, 2900, 2900],
       [   0,    0,    0,    0,    0, 2900]])